In [1]:
import numpy as np
import polynomial_functions as pfn
import em_functions as em
import parameters as prm

%matplotlib inline
from matplotlib import pyplot as plt

import pickle

In [29]:
def H(x, degree):
    switcher = {
        0: 0.63161877774606470129,
        1: 0.63161877774606470129 * x,
        2: 0.44662192086900116570 * (np.power(x, 2) - 1),
        3: 0.25785728623970555997 * (np.power(x, 3) - 3 * x),
        4: 0.12892864311985277998 * (np.power(x, 4) - 6 * np.power(x, 2) + 3),
    }
    return switcher.get(degree, "Polynomial degree exceeded")

# this function defines our hermite basis functions
# x must be a numpy array, a column vector of points
# (x = vector of points at which we seek to evaluate the basis functions)
# dof is the number of degrees of freedom, i.e., the number of basis functions.
def hermite_basis(x):
    theta = np.full((x.shape[0], 4), 1.)
    index_map = index_mapping()

    Hcached = np.zeros((x.shape[0], x.shape[1], 4))
    for d in range(4):
        Hcached[:, :, d] = H(x, d)

    for index in index_map:
        for d in range(1):
            theta[:, index_map[index]] *= Hcached[:, d, index[d]]

    return theta

def old_hermite_basis(x):
    theta = np.full((x.shape[0], 4), 1.)
    index_map = index_mapping()

    for index in index_map:
        for d in range(1):
            theta[:, index_map[index]] *= H(x[:, d], index[d])

    return theta

def index_mapping():
    index = 0
    index_map = {}

    for d in range(0, 4):
        for i in range(0, d + 1):
            if (i == d):
                index_set = (i, i)
                index_map[index_set] = index
                index += 1

                return index_map

In [30]:
x = np.array([[1.], [2.], [3.], [4.], [5.], [6.]])
old_herm = old_hermite_basis(x)
print(old_herm)
herm = hermite_basis(x)
print(herm)
print(herm-old_herm)

[[ 0.63161878  1.          1.          1.        ]
 [ 0.63161878  1.          1.          1.        ]
 [ 0.63161878  1.          1.          1.        ]
 [ 0.63161878  1.          1.          1.        ]
 [ 0.63161878  1.          1.          1.        ]
 [ 0.63161878  1.          1.          1.        ]]
[[ 0.63161878  1.          1.          1.        ]
 [ 0.63161878  1.          1.          1.        ]
 [ 0.63161878  1.          1.          1.        ]
 [ 0.63161878  1.          1.          1.        ]
 [ 0.63161878  1.          1.          1.        ]
 [ 0.63161878  1.          1.          1.        ]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
